package com.batch.domain.exception;

public interface DomainErrorCodes {
    String SHIPMENT_INFORMATION_EMPTY = "SHIPMENT_INFORMATION_EMPTY";
    String SHIPMENT_INFORMATION_FROM_ADDRESS_NOT_FOUND = "SHIPMENT_INFORMATION_FROM_ADDRESS_NOT_FOUND";
    String SHIPMENT_INFORMATION_TO_ADDRESS_NOT_FOUND = "SHIPMENT_INFORMATION_TO_ADDRESS_NOT_FOUND";
    String COUNTRY_CODE_NOT_VALID = "COUNTRY_CODE_NOT_VALID";
    String TRACKING_NUMBER_NOT_FOUND = "TRACKING_NUMBER_NOT_FOUND";
    String ACCOUNT_CHRONOPOST_NOT_CONFIGURED = "ACCOUNT_CHRONOPOST_NOT_CONFIGURED";
    String INVALID_CARRIER_ID = "INVALID_CARRIER_ID";
    String UNABLE_TO_GET_SHIPMENT_LABEL_INVALID_TRACKING_NUMBER = "UNABLE_TO_GET_SHIPMENT_LABEL_INVALID_TRACKING_NUMBER";
    String NO_SHIPMENT_LABEL_FOR_THE_GIVEN_TRACKING_NUMBER = "NO_SHIPMENT_LABEL_FOR_THE_GIVEN_TRACKING_NUMBER";
}
